### ISSUE TITLE
Android Version: Unify all APK's into one single launcher?

### ISSUE THREAD

**Issue by Shockwave508** [NY00123/refkeen#12]
It's been several years since the Reflection Keen APK's were released; would it be possible to combine it all into one single launcher, instead of splitting each plugin across several, separate APK's, as was the case with the Catacomb releases?

**Comment by NY00123** [comment]
Thanks for your interest in the ports!

> It's been several years since the Reflection Keen APK's were released; would it be possible to combine it all into one single launcher, instead of splitting each plugin across several, separate APK's, as was the case with the Catacomb releases?

In case new APKs are ever created, the same should theoretically be possible for the Catacombs, as you can now build combined EXEs for these.

There's still a separate EXE for Keen Dreams, and also another one for Wolfenstein 3D. The main reason is technicalities, mostly in settings accessible from the launcher, which are related to user input and somewhat differ between the games. Even if this is ignored, question is if a user of the source ports will necessarily want to have shared launcher-side settings for all games.

As for the reason there's no new APK file, I'll quote what I wrote in a few forums after the last release:

```
One question that may be asked is what's the status of Android support.
After all, the last release for Android preceded support for Wolf3D, thus
Keen Dreams and the 3D Catacombs are the only covered games.

Thing is, the launcher and game controller support were a preparation
for the Android port, at least partially. Later, it also involved adding
general support for multi-touch input, preparing an Android project, and more.
At the last, SDL2's Android port was already doing most of the important work,
including a piece of Java code which is used in conjunction with
Reflection Keen's and SDL2's C code. Still, work had to be done.

As of now, with the priority being lower, the work required for bringing
Android support back will greatly involve the build system. I already migrated
from Ant to Gradle back in 2019. This broke again after I transitioned from
custom makefiles to CMake for the other platforms. In theory, using CMake
and SDL2 altogether might actually make it easier to build for Android.
However, there's still the issue that I have not just one, but multiple
Android apps / activities to build (Keen Dreams, Catacombs, Wolfenstein 3D).
Also, the general preference of mine, if Android support is ever resurrected,
is to build shared SDL2 and Java code just once if possible. I don't know if
there's a good way to do so while going through build system changes, though.
```

**Comment by NY00123** [comment]
I consider this resolved now:
1. After at least a few restructurings, I got to the state that you can build a single binary supporting all games.
2. It's also possible to build an APK file again. The main change is the migration to a single CMake-based tree.
