### ISSUE TITLE
fail to compile on Pi4

### ISSUE THREAD

**Issue by Exarkuniv** [NY00123/refkeen#15]
i thought i would give this a shot and see if i can get it to run on my Pi4

it starts to compile and then ends up failing quickly

```
/home/pi/RetroPie-Setup/tmp/build/refkeen/src/wolf3d/wl_agent.c:125:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘sodac14::id0_char_t’ {aka ‘char’} inside { } [-Wnarrowing]
 };
 ^
/home/pi/RetroPie-Setup/tmp/build/refkeen/src/wolf3d/wl_agent.c:125:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘sodac14::id0_char_t’ {aka ‘char’} inside { } [-Wnarrowing]
/home/pi/RetroPie-Setup/tmp/build/refkeen/src/wolf3d/wl_agent.c:125:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘sodac14::id0_char_t’ {aka ‘char’} inside { } [-Wnarrowing]
/home/pi/RetroPie-Setup/tmp/build/refkeen/src/wolf3d/wl_agent.c:125:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘sodac14::id0_char_t’ {aka ‘char’} inside { } [-Wnarrowing]
/home/pi/RetroPie-Setup/tmp/build/refkeen/src/wolf3d/wl_agent.c: In function ‘void sodac14::T_Attack(sodac14::objtype*)’:
/home/pi/RetroPie-Setup/tmp/build/refkeen/src/wolf3d/wl_agent.c:2173:3: warningcase label value is less than minimum value for type
   case -1:
   ^~~~
/home/pi/RetroPie-Setup/tmp/build/refkeen/src/wolf3d/wl_agent.c:2174:14: warning: statement will never be executed [-Wswitch-unreachable]
    ob->state = &s_player;
    ~~~~~~~~~~^~~~~~~~~~~
make[2]: *** [CMakeFiles/reflection-sodac14.dir/build.make:342: CMakeFiles/reflection-sodac14.dir/src/wolf3d/wl_agent.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:217: CMakeFiles/reflection-sodac14.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

any pointers would be great

**Comment by NY00123** [comment]
That's a good catch. It's probably a case of "char" being an unsigned type in your toolchain by default, while it was originally configured as signed in Wolf3D for DOS.

Can you pull my last changes and retry building.

**Comment by Exarkuniv** [comment]
first thanks for getting back to me so fast. i
i went and tried it again. 

it goes a lot further but i still get a error

```
/home/pi/RetroPie-Setup/tmp/build/refkeen/src/id91_11/cat_all/catabyss/c4_act1.c: In function â€˜void catabyss::SpawnWallSkeleton(catabyss::id0_int_t, catabyss::id0_int_t)â€™:
/home/pi/RetroPie-Setup/tmp/build/refkeen/src/id91_11/cat_all/catabyss/c4_act1.c:1003:32: error: narrowing conversion of â€˜-1â€™ from â€˜intâ€™ to â€˜catabyss::id0_char_tâ€™ {aka â€˜charâ€™} inside { } [-Wnarrowing]
  id0_char_t xofs[] = {0,0,-1,+1};
                                ^
/home/pi/RetroPie-Setup/tmp/build/refkeen/src/id91_11/cat_all/catabyss/c4_act1.c:1004:32: error: narrowing conversion of â€˜-1â€™ from â€˜intâ€™ to â€˜catabyss::id0_char_tâ€™ {aka â€˜charâ€™} inside { } [-Wnarrowing]
  id0_char_t yofs[] = {-1,+1,0,0};
                                ^
make[2]: *** [CMakeFiles/reflection-catabyss.dir/build.make:258: CMakeFiles/reflection-catabyss.dir/src/id91_11/cat_all/catabyss/c4_act1.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:399: CMakeFiles/reflection-catabyss.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:136: all] Error 2
```

**Comment by NY00123** [comment]
Good to see it went further. The last errors caught me a bit by surprise. Keen Dreams and the Catacombs were built for ARM in the past, but there were probably unrelated differences in the build process.

Can you retry with my last changes?

**Comment by Exarkuniv** [comment]
it built to 100% thank you so much

next quick question. for the games to run. put the binary into the folder with the game?

and if thats how it works is there a way to point the binary to a folder. 
that way the binary can sit in once place and the game in a different?

**Comment by NY00123** [comment]
Great to see the the issue is now resolved.

You can select a folder from the launcher if it has compatible data.
If you don't want to use the launcher, you can run the game with a command from a directory that has compatible game data.

**Comment by Exarkuniv** [comment]
the launcher works great, nice to see that it is working on my pi

but what is the command for running the game within the game data folder. 
im just seeing what will be easier for what im trying to do.

**Comment by NY00123** [comment]
Thanks for the feedback about the launcher and the preceding problems!

As of the last version, you can skip the launcher by adding at least one more command-line argument, unless you specify -fulllauncher or -softlauncher. For more details, you can use -?.

**Comment by Exarkuniv** [comment]
i got it to see my game dir. 
now to get a version of the game that will work. lol

i tryed wolf3d first and the version that works fine with ECwolf. does not work for yours.

**Comment by Exarkuniv** [comment]
nope it seems to be me
it looks like my path is not right. the game starts fine when i find the game through the launcher

here is what im using and it just does not want to work for me

```
refkeen = "/opt/retropie/ports/refkeen/reflection-wolf3d -datadir /home/pi/RetroPie/roms/ports/wolf3d"
```

**Comment by NY00123** [comment]
Are you trying to use a command-line interface or a desktop launcher, like a .desktop file?
What's important is not necessarily that the port's exe (e.g., reflection-wolf3d) resides with the data, but rather that the current working directory is where the data is found.

Either way, -cfgdir refers to where files like reflection-wolf3d.cfg are updated, while -datadir refers to where contents like the dir wl6ac14 (used for keeping CONFIG.WL6 and saved games) and the file wl6ac14.cfg are written to.

**Comment by Exarkuniv** [comment]
i have Retropie on my Pi4. and that uses a shell script and runcommands to make everything work. 

so 
```
refkeen = "/opt/retropie/ports/refkeen/reflection-wolf3d -datadir /home/pi/RetroPie/roms/ports/wolf3d"
```
is a line from what is called the emulators.cfg. which is what the runcommand uses to start the game, when you select the game from the list.

as you see the reflection-wolf3d is sitting in the opt and the game data is in the home. 
it is a pain to easyly get the game file into the opt folders and if i put the game binary into the game dir it might get deleted. 

```
/home/pi/RetroPie/roms/ports/wolf3d
```
is where my game data is currently sitting.

**Comment by Exarkuniv** [comment]
just for the heck of it i ran this in command-line
```
 /opt/retropie/ports/refkeen/reflection-wolf3d -cfgdir /home
```
and the game starts no problem. 

how does the reflection-wolf3d know where the game data is sitting. i looked at reflection-wolf3d.cfg and there is no dir line pointing to it?

**Comment by Exarkuniv** [comment]
now that i have been messing around with it. i will just leave the menu as part of it. since you can pick what games you want to play easily.

thanks for all your help

**Comment by NY00123** [comment]
Thanks again for the feedbacks! I've just pushed an update which covers a few clarifications related to starting a game.

I don't think that you have to use -cfgdir or -datadir.
1. -cfgdir is used to specify the location of Reflection Keen's new cfg files, like reflection-wolf3d.cfg, as well as gamecontrollerdb.txt (if present). If not specified, the path in use is $XDG_CONFIG_HOME/reflection-keen, with ~/.config/reflection-keen being the default.
2. -datadir is used to specify where are modifiable game files stored. This covers files like Wolf3D's CONFIG.WL6 or saved games. There are also txt files used for remembering the locations of game installations manually added via the launcher. If not specified, the path is $XDG_DATA_HOME/reflection-keen, with ~/.local/share/reflection-keen as the default.

**Comment by Exarkuniv** [comment]
thank you for that. 
your clarifications do help. for now i will use it as is and see if anyone says anything they would like done to make it more straight forward. (more cuz people now are lazy)
